import type { NextPage } from 'next'
import Head from 'next/head'
import {useEffect} from 'react';
import Router from "next/router"

const Home: NextPage = () => {
  useEffect(()=>{
   const {pathname} = Router
   if(pathname == '/' ){
       Router.push('/blog')
   }
  },[])
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
